### ISSUE TITLE
Slapper.Automapper crashes in certain a rare corner case; fix attached

### ISSUE THREAD

**Issue by sharpe5** [SlapperAutoMapper/Slapper.AutoMapper#12]
Hi,

Firstly, Slapper.Automapper is just awesome, thanks for the excellent work!!!

I've had Slapper.Automapper crash with a null pointer exception.

Imagine that we have a large SQL query, and part of it comes back as null:

![image](https://cloud.githubusercontent.com/assets/1290916/7595468/29e2f38c-f8df-11e4-81e7-d5700f550b10.png)

This means that everything in the POCO is null, and nothing should be added to its parent POCO (which is class `PingOrder` which contains `List<PingTicket> Tickets;`):

	[DataContract]
	public class PingTicket
	{
		// Must have parameterless constructor.
		public PingTicket()	{ }

		[DataMember]
		public long? TicketId { get; set; }

		[DataMember]
		public decimal? Quantity { get; set; }
	}

The code crashes in this line, as `identifierValue` is null:
`identifierHash += identifierValue.GetHashCode() + type.GetHashCode();`

the code is in this function:
`public static Tuple<bool, object, int> GetInstance(Type type, IDictionary<string, object> properties)`

The fix I applied was to replace this:

`identifierHash += identifierValue.GetHashCode() + type.GetHashCode();`

with this:

`if (identifierValue != null)`
`{`
  `identifierHash += identifierValue.GetHashCode() + type.GetHashCode();`
`}`

When this function was entered, the contents of the `properties` parameter was this:
`properties["ticketid"] = null`
`properties["orderid"] = null`

This meant that `identifierValue` was null, and `identifierValue.GetHashCode()` failed as you can't get a hash on a null value.

I would submit a push request, but unfortunately I can't as I'm at work.

**Comment by smt52** [comment]
I'm not sure whether this fix would create other issues, is this the best way to handle it?

**Comment by smt52** [comment]
This fix certainly stops the crash. But, this fix seemed to have other knock on effects which are not good. It ended up adding lots of redundant entries to the `List<Tickets> Tickets` list, every entry contained TicketId=null and Quantity=null.

**Comment by smt52** [comment]
I guess the central question is this: what should happen when there is holes in the data, like this? If we have `List<Tickets> Tickets`, we want this list to be empty - and not crash the code, or contain nothing but 7 repeats of `TicketID = null` and `Quantity = null`.

![image](https://cloud.githubusercontent.com/assets/1290916/7596348/e60788c0-f8e4-11e4-9eda-f9b3d1bd23b4.png)

**Comment by smt52** [comment]
Again, Slapper.Automapper is a simply awesome piece of code, it is an incredible piece of work!!

**Comment by smt52** [comment]
This fix works slightly better:

Roll back to v1.0.6, then replace:

`identifierHash += identifierValue.GetHashCode() + type.GetHashCode();`

with this:

`identifierHash += identifierValue != null ? identifierValue.GetHashCode() : 0 + type.GetHashCode();`

This fix means that if there is a block of nulls, like above, `List<Tickets> Tickets` contains a single item, with `TicketID = null` and `Quantity = null` (the list should be empty, so its still not ideal, but better than a crash or multiple instances of `TicketID = null` and `Quantity = null`, as in the previous fix).

**Comment by fru** [comment]
We are experiencing the same problem. This fix helped tremendously! Would you consider merging it into the project for the next release?

**Comment by sharpe5** [comment]
FYI, this issue has been fixed in the latest release.

**Comment by odelvalle** [comment]
Thanks @sharpe5 .. Exactly, has been fixed in version 1.0.0.7 and published to Nuget.
