### ISSUE TITLE
Looking for new Maintainer for Slapper.AutoMapper

### ISSUE THREAD

**Issue by randyburden** [SlapperAutoMapper/Slapper.AutoMapper#18]
It makes me really happy to see that Slapper.AutoMapper has gained usage in the community but I no longer have time to maintain Slapper.AutoMapper so I am looking for someone to take over as the primary maintainer and contributor of the project. I no longer use Slapper.AutoMapper in my own personal work and have been busy working on several other open source initiatives that are consuming all of my time including [Nano](https://github.com/AmbitEnergyLabs/Nano) and [Sequelocity](https://github.com/AmbitEnergyLabs/Sequelocity.NET).

If you feel that you would be a good steward of the project, are actively using the library yourself in one or many different projects, have the time to review and accept community contributions and pull requests, and are willing to put in the effort to continue to evolve the project then please respond to this thread and state a little about yourself and why you think you would be the right person to take on the role of the maintainer of this project.

I will give this thread a week for responses and discussion before making a decision at which point I will transfer ownership of the Slapper.AutoMapper GitHub repository and the NuGet package to the new maintainer.

**Comment by odelvalle** [comment]
I could go on with this project. I currently use your project in many of my projects. This library https://github.com/odelvalle/NET-Database-query-layer  use Slapper internally to convert DataReader in DTO. 

In other projects, I use slapper too with NH and through a IResultTransformer implementation,I get a ExpandoObject to use in Slapper.

Thank you very much for trying to keep this project alive

**Comment by randyburden** [comment]
@odelvalle I've moved the project from my under my personal profile to its own organization. I've added you as a member so I'll need you to confirm the email that GitHub sends you at which point I can grant you appropriate contributor permissions. I'll also need your NuGet username so that I can add you as an owner of the package in order to release new versions. Let's use this thread as our primary means of communication.

**Comment by odelvalle** [comment]
@randyburden I have already confirmed github email.. My username in NuGet is odelvalle ;)

**Comment by randyburden** [comment]
@odelvalle You are now a member of the SlapperAutoMapper GitHub organization and should have write access to the repository and I've added you as an owner of the Nuget package. I look forward to seeing yours and others contributions merged into the project and future successful releases without my involvement as yourself and others help shape the future direction of the project. If you ever need anything please reach out.

**Comment by randyburden** [comment]
@odelvalle I forgot to mention that if you wish for yourself to show up as a member of the organization you'll need to set your status from private to public on this page I believe: https://github.com/orgs/SlapperAutoMapper/people

**Comment by odelvalle** [comment]
Done!
