### ISSUE TITLE
Object 'this' properties

### ISSUE THREAD

**Issue by xzaz** [SlapperAutoMapper/Slapper.AutoMapper#20]
I got the following dynamic object:
```
PERSON_NAME
DEPARTMENT_NAME
```

With the classes:
```
class Person
{
public string Name {get;set;}
public Department Department {get;set;
}

class Department
{
public string Name {get;set;}
}
```

When using the Automapper the Department object is created and the name is filled. Due the PERSON_ prefix for ```this``` object the Person.Name is not filled. Is there any way to achieve this without editing the raw dynamic data?

**Comment by odelvalle** [comment]
HI @xzaz 

Are you using the last version of Slapper? 1.0.7. If true: can you create test for this error?

Thanks...

**Comment by xzaz** [comment]
https://github.com/xzaz/Slapper.AutoMapper/commit/79c39887c0f2d89849e138481ab4daaa676e0d53

**Comment by odelvalle** [comment]
Hi @xzaz 

In your ExpandoObject Person, person.PERSON_NAME is incorrect. In your object person, the property is called Name 

This test pass!

```csharp
[Test]
public void Can_Populate_Self_Object_Properties()
{
	dynamic person = new ExpandoObject();
	person.NAME = "Clark"; // Changed PERSON_NAME by NAME
	person.DEPARTMENT_NAME = "IT";

	var list = new List<dynamic> { person };

	var pPerson = Slapper.AutoMapper.MapDynamic<Person>(list).FirstOrDefault();

	Assert.NotNull(pPerson);
	Assert.NotNull(pPerson.Name);
	Assert.NotNull(pPerson.Department.Name);
}
```

**Comment by odelvalle** [comment]
if you can't edit or change the raw dynamic data, then the property Name in class Person, must be called Person_Name.

```csharp
public class Person
{
       public string Person_Name { get; set; }
       public Department Department { get; set; }
}
```

**Comment by xzaz** [comment]
So yes, that is the 'problem' I want to map the `PERSON_` to the `this` object. Or is this against the rules?

**Comment by xzaz** [comment]
https://github.com/xzaz/Slapper.AutoMapper/commit/3f4c551d8c26fc7efceb9074a4c2c56d0e8fab38

This does it for me, everything checks out. Meh.

**Comment by odelvalle** [comment]
Sorry @xzaz 

This is against the rules... you can change class Person if can't edit or change the raw dynamic data.
