### ISSUE TITLE
Avoid Nested Duplicate Instances

### ISSUE THREAD

**Issue by mtschneiders** [SlapperAutoMapper/Slapper.AutoMapper#23]
Considering a simple scenario with a nested object mapping, I'm looking for a way to avoid duplicate instances when the child Identifier match.

Consider the following scenario:

**Classes:**
```
public class Employee
{
	public int Id {get;set;}
	public string Name {get;set;}
	public Department Department {get;set;}
}

public class Department
{
	public int Id {get;set;}
	public String Name {get;set;}
}

```
**DataSet:**

Id | Name | Department_Id|Department_Name
------------ | -------------| -------------| -------------
1|Employee1|1|Department1
2|Employee2|1|Department1

```

Dictionary<string, object> item1 = new Dictionary<string, object>()
{
    { "Id",1 },
    { "Name" ,"Employee1" },
    { "Department_Id", 1 },
    { "Department_Name", "Department1" }
};

Dictionary<string, object> item2 = new Dictionary<string, object>()
{
    { "Id", 2},
    { "Name" ,"Employee2" },
    { "Department_Id", 1 },
    { "Department_Name", "Department1" }
};

List<Dictionary<string, object>> list = new List<Dictionary<string, object>>() { item1, item2 };
var employeeList = Slapper.AutoMapper.Map<Employee>(list).ToList();

Assert.AreEqual(employeeList[0].Department, employeeList[1].Department); //false

```

We're looking for ways to avoid duplicating strings from child objects in memory (in this case, the department name).
With the current implementation of the AutoMapper, is there a way to make this work?

**Comment by odelvalle** [comment]
Sorry @mtschneiders 

Slapper.AutoMapper always create the new instance for nested members. I'll look, maybe this is fixable

Thanks!
