### ISSUE TITLE
Slapper behavior for dynamic object's child objects

### ISSUE THREAD

**Issue by digaomatias** [SlapperAutoMapper/Slapper.AutoMapper#32]
In my application we have a scenario where the dynamic objects returned from the query can have a null child. 

Consider the user object being like this:
```C#
public class User 
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Address Address { get; set; }
}
```

For example, if I do a query to retrieve one user and it doesn't have an address yet:
```SQL
SELECT 
    U.Id, 
    U.Name, 
    U.Address_Id 
FROM Users U
```

This is the dynamic object returned:
> {{ DapperRow, Id = '1', Name = 'Dummy User', Address_Id = NULL }}

What happens here when I use AutoMapper.MapDynamic<User>(result) is that the User object created contains an empty instance of Address. Slapper maps the null Address_Id into an empty instance of Address with Id=0. 
This could cause errors if after retrieving the object from the database, we try to save it back. It would have a reference to an object with id=0, the update on the database would break with foreign key constraint.

Is there a way to tell Slapper to not map null values to empty child objects? I would prefer to map null instead.

**Comment by rstraszewski** [comment]
I have exactly the same problem. Dapper built-in mapping is working in a way, that if splitting property is null, the whole object is null I think. Here I have object filled with nulls, which will create errors. It would be nice to set child object to null, if id is null for example...

**Comment by odelvalle** [comment]
pull request #28 merged with Master
