### ISSUE TITLE
Using Slapper causes Unit Tests to fail with serialization errors

### ISSUE THREAD

**Issue by szc001** [SlapperAutoMapper/Slapper.AutoMapper#37]
As per the title.  If I use Slapper to convert anything, my unit tests are all aborted (I am using MSTest).

The underlying issue seems to be a Serialization issue.  But marking my POCOs as Serializable does not solve this.

**Comment by odelvalle** [comment]
Include Cleanup tests and clear Slapper Cache

```cs
[TestCleanup] 
public void Cleanup() 
{ 
   Slapper.AutoMapper.Cache.ClearInstanceCache(); 
}

**Comment by szc001** [comment]
Well, my project came to an end since then so I've gone without Slapper.  That said, it would be good to include this on the wiki.

Thanks for your reply.
