### ISSUE TITLE
Cannot use Enumerable.Empty<T>() as default property value

### ISSUE THREAD

**Issue by ike86** [SlapperAutoMapper/Slapper.AutoMapper#42]
**Problem**
If I use `Enumerable.Empty<T>()` as a default value on properties (or fields) like `IEnumerable<T> MyProp`,
I get a `System.Reflection.TargetException` with message _Object does not match target type_.

**Expected**
`MyProp` should be overwritten by the mapped values.
_or_ see #43

**Code for repro**
in _ReadMeTests.cs_

``` csharp
public class Customer
{
    public int CustomerId;
    public string FirstName;
    public string LastName;
    public IEnumerable<Order> Orders = Enumerable.Empty<Order>(); // note this
}

// ...

public void I_Can_Map_Nested_Types_And_Resolve_Duplicate_Entries_Properly_Using_Dynamics() // will fail

// ...
```

**Comment by ike86** [comment]
This is related to #41

**Comment by odelvalle** [comment]
Fixed. Pull request #41 merged in master
