### ISSUE TITLE
Slapper migration to NET Framework 4.X and NET Standard 1.X

### ISSUE THREAD

**Issue by odelvalle** [SlapperAutoMapper/Slapper.AutoMapper#44]
Hi all,

Now Slapper built on NET framework 4.0. I'm thinking to migrate Slapper from NET 4.0 to NET 4.6.1 and NET Standard 1.5. 
- What do you think about this? 
- What would be better for us, 4.6.1 + NET Standard 1.5 or 4.5 + NET Standard 1.1?
- Do you prefer to have 2 branches on Github and maintain compatibility with NET 4.0 for futures pull request?

In any case, in Nuget we'll continue to have only one package that includes Slapper to NET 4.0 and Slapper to NET 4.X + NET standard 1.X.

Thank in advance.

**Comment by mmierzwa** [comment]
Moving to .Net Standard is a great idea. I've just started working on a ASP.Net Core project and I'm eagerly waiting for this. 

I guess 4.6.1 + Net Standard 1.5 might be a better choice from the future perspective of this library. Upgrading will break compatibility anyway.

2 branches sounds good from the user's perspective but will cost you and other contributors some extra work :)

**Comment by silkfire** [comment]
What's the ETA on the port? I'm eagerly awaiting this so I can use it my new .NET Core project.

**Comment by erikpowa** [comment]
@silkfire You can check my fork! I made few changes (+ got ~3x faster mapping).

**Comment by odelvalle** [comment]
https://github.com/SlapperAutoMapper/Slapper.AutoMapper/tree/master.core Please, check master.core branch. 4.6.1 + Net Standard 1.5

Core branch will be merged soon with master.

**Comment by wyf5188** [comment]
Is that .NET Core 1.0/1.5 version available on NuGet yet?

**Comment by odelvalle** [comment]
@wyf5188 No. Not yet. I need a little more time to merge two branch.

**Comment by stefanosandes** [comment]
So, any chance to have an pre-release on nuget?

**Comment by odelvalle** [comment]
@stefanosandes good idea. This weekend I'm going to publish pre-release version on nuget

**Comment by stefanosandes** [comment]
@odelvalle cool! Thanks for your effort!!

**Comment by odelvalle** [comment]
@stefanosandes @wyf5188  https://www.nuget.org/packages/Slapper.AutoMapper/2.0.0.9-beta :-) Done!

**Comment by PedroArvy** [comment]
Awesome work and much appreciated!

**Comment by jlentrichia** [comment]
Fantastic.  Thank you.

**Comment by guillaumejay** [comment]
Thanks for the preRealease !  Are you planning to do a standard release ?

**Comment by Rishab1988** [comment]
Getting the following error when trying to compile against .net Standard 2.0 
Error; Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0656	Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

**Comment by odelvalle** [comment]
Merged PR to upgrade Slapper.AutoMapper to NET Standard 2.1 && NET Core 3.1. The package will be published this weekend. Thanks to all and specially to @takinosaji  by PR.
