### ISSUE TITLE
Library DLL version wrong (reads 1.0.0.7) in nuget package for 1.0.0.9

### ISSUE THREAD

**Issue by reisenberger** [SlapperAutoMapper/Slapper.AutoMapper#47]
Steps to reproduce:

+ Download or install Slapper.AutoMapper.1.0.0.9.nupkg
+ Inspect the DLL version number on `Slapper.dll` using Nuget Package Explorer, File Explorer->right-click->properties, or right-click->properties the reference in Visual Studio: dll version number reads 1.0.0.7

![image](https://cloud.githubusercontent.com/assets/9608723/20358609/60a4180c-ac24-11e6-9e87-9c4f4774c5be.png)

This is causing potentially two kinds of issues:

+ Users may have to add an additional binding redirect to their config files, to avoid experiencing `System.IO.FileNotFoundException : Could not load file or assembly 'Slapper, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

+ Nuget Package Manager dialogs in Visual Studio tell me I have 1.0.0.9 installed, but that 1.0.0.8 is the latest version

**Comment by kattianita** [comment]
this is still an issue.. ? I still see this as 1.0.0.7 instead of 1.0.0.9..
