### ISSUE TITLE
Mapping nullable Guids fails

### ISSUE THREAD

**Issue by FilipFilipov** [SlapperAutoMapper/Slapper.AutoMapper#56]
If you call MapDynamic for a value where a string should be converted to a Guid?, you get a `System.Exception : Invalid cast from 'System.String' to 'System.Guid'.` I looked through the code and the GuidConverter's CanConvert method indeed does not check for nullable Guids.

**Comment by FilipFilipov** [comment]
Also in `ConvertValuesTypeToMembersType` you should probably check if the member type is nullable with the same underlying type as the valu, so you don't try to convert a Guid to a Guid? for example.

**Comment by randyburden** [comment]
The fix for this has been released in [v2.0.2](https://github.com/SlapperAutoMapper/Slapper.AutoMapper/releases/tag/v2.0.2) and pushed to [NuGet](https://www.nuget.org/packages/Slapper.AutoMapper/2.0.2)
