### ISSUE TITLE
Thank-you!

### ISSUE THREAD

**Issue by ToddThomson** [SlapperAutoMapper/Slapper.AutoMapper#63]
Just a quick thank-you from [Entities.Sqlite](https://github.com/achilles-software/entities.sqlite). We utilized a few of your ideas and used some modified source from your project. Your project license will be included as required.

**Comment by randyburden** [comment]
@ToddThomson, congrats on your new open source project. I'm glad the numerous contributors to this project over the years helped inspire and play a part in the development of yours and others projects. Maintaining open source projects is not easy so best of luck to you! =)
