### ISSUE TITLE
Slapper Not Working When Type of Property ICollection

### ISSUE THREAD

**Issue by dreamid27** [SlapperAutoMapper/Slapper.AutoMapper#65]
Hi, thank for your awesome package. really - really help me. I Appreciate it .

but I have some problem, when my model,  I have the property which is the type is **ICollection** , he is not working and gives the error.

![image](https://user-images.githubusercontent.com/22621375/45544390-5b5ce600-b841-11e8-8c23-baa87e334e9b.png)

![image](https://user-images.githubusercontent.com/22621375/45544560-dd4d0f00-b841-11e8-85e0-59b5134e9e52.png)

but when I, change the type to type property **IList**, work perfectly ! 

this is a bug ?  

cause I see not consistent if I use different type ICollection and IList in each model. just for making the Slapper Work.

Thank you. sorry for my bad English.

**Comment by odelvalle** [comment]
hi @dreamid27 can you write a test to reproduce the problem?

thank a lot
