### ISSUE TITLE
Getting the following error when trying to compile against .net Standard 2.0

### ISSUE THREAD

**Issue by Rishab1988** [SlapperAutoMapper/Slapper.AutoMapper#66]
Error; Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0656	Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

_Originally posted by @Rishab1988 in https://github.com/SlapperAutoMapper/Slapper.AutoMapper/issue_comments#issuecomment-423785842_

**Comment by dennisvanderpool** [comment]
I have the same thing now. Just added slapper 2.0.1 via NuGet into a Dotnet Core 3.1 lib.

**Comment by dennisvanderpool** [comment]
Got it fixed by adding Microsoft.CSharp via NuGet to the library. Should this be marked as a dependency for Slapper?
