### ISSUE TITLE
Support for abstract classes

### ISSUE THREAD

**Issue by Towa** [SlapperAutoMapper/Slapper.AutoMapper#8]
One feature that is missing is support for abstract classes.
I think code says more than 1000 words:

public abstract class Request {
    public string Message { get; set; }
}

public class GetCustomerRequest : Request {
    public Guid CustomerId { get; set; }
}

public class GetDepartmentRequest : Request {
    public Guid DepartmentId { get; set; }
}

```var request = Slapper.AutoMapper.Map<Request>(dictionary);```

I implemented support for this for my current project, but I am not sure if that is the direction you want to take. Anyway you can find my code here: https://github.com/Towa/Slapper.AutoMapper/commit/7434a713938d957e834450fb2e2362decf59ce2e

**Comment by odelvalle** [comment]
Pull Request #38, TypeActivator inlcuded
