### ISSUE TITLE
Can Map to an Interface Property

### ISSUE THREAD

**Issue by pretzelfisch** [SlapperAutoMapper/Slapper.AutoMapper#9]
I have a class that I want to map a dynamic object to one of it's properties is an interface that I would like mapped as a concrete class Is there a way to do this?  
public MyClass
{
public string email{get;set;}
public ISomeInterface data{get;set;}
}
public MyData : ISomeInterface
{
public string SomeProperty{get;set;}
}

**Comment by mogijoseph** [comment]
Any word on when the next version with this fix will be released?

**Comment by odelvalle** [comment]
Pull request #38 TypeActivator included
